### ISSUE TITLE
Wait for original download to complete

### ISSUE THREAD

**Issue by joydashy** [JohnDoee/flexget-cross-seed#2]
I wonder if there's a solution for my problem possible through this plugin. First of all, it works great in general, but the following happens:

Download starts on site A, file is create (some .mkv for example)
Same file is detected on site B, while A is downloading, download for site B starts.

Now the problem is that a large amount of the download will come from site B, as A was not yet finished. So ideally there would be a way to halt B until A is finished, so site B is 100% cross-seed.

Any ideas?

**Comment by JohnDoee** [comment]
I move completed releases to a different folder and configured autotorrent to not look into the download folder with incomplete stuff.

**Comment by joydashy** [comment]
Hmm yes, that makes sense, will try that, thanks!
