### ISSUE TITLE
'Logger' object has no attribute 'verbose'

### ISSUE THREAD

**Issue by stumpyofpain** [JohnDoee/flexget-cross-seed#3]
hi

i just installed flexget on my ubuntu lxc and configured it.
while testing it with my first server i get the following error:

> 2020-04-10 09:30:09
CRITICAL
manager
btf
task An unexpected crash has occurred. Writing crash report to /root/flexget/crash_report.2020.04.10.093009563415.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 3.1.49
2020-04-10 09:30:09
CRITICAL
task
btf
task BUG: Unhandled error in plugin cross-seed: 'Logger' object has no attribute 'verbose'

Errorlog
https://pastebin.com/TRWgGLZs

config
https://pastebin.com/EfqemhVL

what did i do wrong?

**Comment by JohnDoee** [comment]
Seems like Flexget changed logging. I've updated the plugin to try and be compatible with both old and new flexget.
