### ISSUE TITLE
Not matching

### ISSUE THREAD

**Issue by HarringtonTom** [JohnDoee/flexget-cross-seed#4]
A lot of RSS feeds don't actually show the file name with dots. Therefore they aren't matching. 

RSS feed = 1080p AMZN WEB-DL 
Actual File Name = 1080p.AMZN.WEB-DL. 

if I remove the dots from the filename, the torrent is found, but If I don't it just says all the torrents are undecided. 

I'm guessing there is some way I can get around this by using the "manipulate" in the config. But how would I do that?

**Comment by JohnDoee** [comment]
Is the dot in the end of "Actual File Name" a typo ?

When matching it replaces `-` `_` and `.` with spaces and lower-cases the name. Well, it should at least.

When matching it should look like this, with your example.
RSS feed = `1080p AMZN WEB-DL` -> `1080p amzn web dl`
Actual File Name = `1080p.AMZN.WEB-DL.` -> `1080p amzn web dl ` <- (there's a space)

**Comment by HarringtonTom** [comment]
Actually I've just realized it might be because in AMZN WEB-DL's. The audio is named as DDP5.1 but on the RSS feed it's named as DD+ 5.1. Is it possible for it to only read up to 1080p.AMZN.WEB-DL of the file name such as Stargirl S01E01 1080p AMZN WEB-DL?

**Comment by HarringtonTom** [comment]
Nevermind got it working using this. Probably not the best way to do it but it works how I want it to: 

tasks:
  # Site EXAMPLE
  EXAMPLE:
    rss: 
    template: cross-seed
    download: /home/user/Downloads/
    manipulate:
      - title:
          replace:            
            regexp: '[+]' #Replaces + sign with P
            format: 'P'
      - filename:
          from: title
      - filename:
          replace:            
            regexp: 'DDP ' #Removes the space between DDP 5.1 to create DDP5.1 like in file name
            format: 'DDP'
      - title:
          from: filename
      - title:
          replace:            
            regexp: ' ' #Adds dots in the spaces
            format: '.'

**Comment by JohnDoee** [comment]
You left your key in the RSS link, probably not what you wanted.

I've been thinking about a smart way to solve it and I got no smart solutions. So whatever you *can* get working is probably the best, even if it's just a one-off.

**Comment by HarringtonTom** [comment]
Yeah just been trying to edit it but it wouldn't let me haha. Its deleted now.

**Comment by HarringtonTom** [comment]
Thanks for the awesome Autotorrent though. Its so good.

**Comment by HarringtonTom** [comment]
Hi man sorry for reopening. Do you happen to know how I can get it working on PTP? Here is what the RSS title looks like: 

Ginger Snaps [2000] by John Fawcett - H.264 / Blu-ray / MKV / 1080p / Remux / Collector's Edition / With Commentary [ Ginger.Snaps.2000.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-TDD ]

So basically I need to grab what's in the [ ]

**Comment by JohnDoee** [comment]
```
   manipulate:
      - title: 
          extract: '\[ ([^[]+) \]$'

```

something like this ?

**Comment by HarringtonTom** [comment]
You my friend are a genius! Where did you learn the syntax for this?

**Comment by JohnDoee** [comment]
I might've seen the PTP feed and made that once. If you need others then I might have them too.

Manipulate generally is from https://flexget.com/Plugins/manipulate but I think you know that already.

**Comment by HarringtonTom** [comment]
Don't think I need any others atm, thanks anyway. Was just asking for the future
